version: '3.8'
services:
  docker-mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pair
    ports:
      - 3307:3306

  pair:
    depends_on:
      - docker-mysql
    build:
      context: ./
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/app
      - ./.m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    ports:
      - 8082:8082
      - 35729:35729
      - 5005:5005
    environment:
      - MYSQL_HOST=docker-mysql
      - MYSQL_PORT=3306
      - MYSQL_SCHEMA=pair
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - PORT=8082
      - SHOW_SQL=false
      - HIBERNATE_DLL-AUTO=none

